repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: external-dns-cloudflare
    chart: stable/external-dns
    version: 1.7.9
    namespace: external-dns-route53
    values:
      - domainFilters: [{{ env "FQDN" }}]
        rbac:
          create: true
        txtOwnerId: z2jh-aws
        provider: aws
        domainFilter: jupyterhub
        aws:
          region: {{ requiredEnv "AWS_REGION" }}
          zoneType: {{ env "AWS_ZONE_TYPE" | default "public" }}
          credentials:
            accessKey: {{ requiredEnv "AWS_ACCESS_KEY_ID" }}
            secretKey: {{ requiredEnV "AWS_SECRET_KEY" }}
  - name: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.6.16
    namespace: nginx-ingress
    values:
      - rbac:
          create: true
        controller:
          replicaCount: 2
          config:
            use-proxy-protocol: "true"
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          publishService:
            enabled: true
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v0.8.1
    namespace: cert-manager
    values:
      - ingressShim:
          defaultIssuerName: letsencrypt-prod
          defaultIssuerKind: ClusterIssuer
